### ISSUE TITLE
Better units specification

### ISSUE THREAD

**Issue by padpadpadpad** [fawda123/rStrava#10]
Would there be any way to have a stand alone units function that includes something that tells you whether it is the elevation/distance/time/the other unit I can't work out what it is on each athlete's profile.

Haven't every played with Xml but will have a think.

Would make downstream transformation so much easier for conversions of get_activities() and distance()

**Comment by fawda123** [comment]
The `athl_fun` that doesn't require a token returns the units but these are for the info scraped from the public web pages.  The readme has the example.  

I can't find any info about the data from the API but it looks like distance and elevation are in meters and time is in seconds (making speed in m/s).  Do you mean having a function that converts the units (e.g., km to miles) for display on the plots?

**Comment by padpadpadpad** [comment]
Kind of. I was worried if the data from the API comes down in the format of the scraped info then the `get_dists()` function will give the wrong thing. If it doesn't then that is great and you can close this.

**Comment by fawda123** [comment]
I need to dig around the API documentation a bit more to see if the units ever change but it looks like that'll also be in meters and seconds.  It would be simple enough to add an argument to the plotting functions to change the units on the fly, so long as the raw data are always the same units.

**Comment by fawda123** [comment]
I just added a units argument to the elevation profile and heat map plotting functions.  This is hard-coded in each so it's not a stand-alone function but I think this is okay for now since these are the only two that report units.  8d3b3e603a46c97e31ba178a471ad4aa92185814
```r
# units can be metric or imperial
get_elev_prof(my_acts, key = mykey, units = 'imperial')
```

**Comment by fawda123** [comment]
The object returned from `compile_activities` is now an `actframe` object that has either imperial or metric units depending on the `units` argument.  Distance, speed, and elevation are in km, km/hr, and m if metric and mi, mi/hr, and ft if imperial.  There are two attributes appended to the `actframe` object that has this info.  They are used downstream for the plotting functions to show the correct units in the input object.  I think this is a good way to handle conversions.  Also, the speed and distance values are in better units to query, e.g., km/hr and not m/s.   474023c29edae481a825ea046c4003ae792a67f7
```r
my_acts <- get_activity_list(stoken)
acts_data <- compile_activities(my_acts)

# show attributes
attr(acts_data, 'unit_type')
attr(acts_data, 'unit_vals')

# downstream conversion of units 
my_acts <- compile_activities(my_acts, acts = 1, units = 'imperial')
get_heat_map(my_acts, key = mykey, alpha = 1, add_elev = T, col = 'Spectral', size = 2, maptype = 'satellite')
```
![rplot](https://cloud.githubusercontent.com/assets/3086881/18611437/d2e9d780-7cfe-11e6-9185-bed25c21d5cb.png)
