### ISSUE TITLE
Error in strava_oauth

### ISSUE THREAD

**Issue by Mikmonken** [fawda123/rStrava#100]
Think i resolved it (not sure what resolved it but installing Pacman and then running 

`pacman::p_load(rStrava, dplyr, sf, purrr, tmap, raster)`

prompts a Strava authentication window, so can now play a bit
---------
Hi this is more than likely a user error, never used R before but want to use rStrava to create some artwork as per https://www.jordanhutchings.com/blog/2023-08-01-strava-api-viz/.

My issue is that when running

`stoken <- httr::config(token = strava_oauth(app_name, app_client_id, app_secret, app_scope="activity:read_all"))`

I get the following error  Error in strava_oauth(app_name, app_client_id, app_secret, app_scope = "activity:read_all") : 
  could not find function "strava_oauth"

I've used my Strava API previously for an app called Elevate which is still working and drawing fine (todays API graph shows it's pulled the 32 activities I've done recently, so pretty sure that Im linking the API to the rStrava headings properly.

app_name <- 'myappname' # chosen by user
app_client_id  <- 'myid' # an integer, assigned by Strava - Client ID on https://www.strava.com/settings/api
app_secret <- 'xxxxxxxx' # an alphanumeric secret, assigned by Strava - Client Secret on https://www.strava.com/settings/api

rStrava is installed

> a<-installed.packages()
> packages<-a[,1]
> is.element("rStrava", packages)
[1] TRUE _(that means it's installed right?)_

I'm sure this is user error.... but any help/trouble shooting would be appreciated.  

R 4.3.2 GUI 1.80 Big Sur Intel build (8281)
Mac OS Sonoma 14.2

**Comment by fawda123** [comment]
The `strava_oauth()` function is part of rStrava, so you need to load the package before you run the authentication (`library(rStrava)`).
