### ISSUE TITLE
Bug when calling `get_activity_list()` with the `id` argument

### ISSUE THREAD

**Issue by choisy** [fawda123/rStrava#101]
Let's retrieve the activity streams of today's only activity, using the `after` argument:
```
a1 <- get_activity_list(stoken, after = lubridate::today() - 1)
b1 <- compile_activities(a1)
d1 <- get_activity_streams(b1, stoken)
```
It works perfectly. Now let's do the same except that we call `get_activity_list()` with the `id` argument instead of the `after` argument:
```
a2 <- get_activity_list(stoken, id = b$id)
b2 <- compile_activities(a2)
d2 <- get_activity_streams(b2, stoken)
```
Here, calling `get_activity_streams()` generates this error:
```
Error in get_activity_streams.actframe(b2, stoken) : 
  Cannot get streams for manual activities: NA
```
Furthermore, `a1` and `a2` are, against expectations, different:
```
identical(a1, a2)
length(a1[[1]])
length(a2[[1]])
identical(a1[[1]], a2[[1]][names(a1[[1]])])
```
Also, when you look at how `a1` and `a2` for the common slots, you can see that they are different for the `resource_state` and the `map` slots:
```
a1[[1]]$resource_state
a2[[1]]$resource_state

a1[[1]]$map
a2[[1]]$map
```

**Comment by fawda123** [comment]
@choisy thanks for pointing this out. The data returned from the API is different if requesting with an activity id.  I guess they changed this at some point.  I added a little fix that makes the data output the same between the two requests and it should work now.
