### ISSUE TITLE
`get_activity_list` no longer returning some variables

### ISSUE THREAD

**Issue by skgrange** [fawda123/rStrava#102]
Hello,
Many thanks for the development of this package. The `get_activity_list` function is now only returning missing values for the `suffer_score` and `average_watts` variables. Is this by design and reflects a change on what variables can be accessed via the API, or is this a specific package issue? Many thanks for help! 
Stuart.

**Comment by fawda123** [comment]
@skgrange my guess is that it's an API issue.  The format of what's returned by the API request changes often and this is out of my control.

**Comment by skgrange** [comment]
Hello, ok, not a problem. Thanks for the information.
