### ISSUE TITLE
The floating point issue of #104 also impacts the responses

### ISSUE THREAD

**Issue by mkiang** [fawda123/rStrava#106]
It looks like the floating point issue you found in #104 also impacts the responses. Using the example as #104, when I get back a list of segment efforts, there is a loss of precision in the ID. For example:

```
> x <- get_efforts_list(
+     stoken,
+     id = "229781",
+     start_date_local = "2024-09-01T07:00:14Z",
+     end_date_local = "2024-09-01T23:59:59Z"
+ )
> x[[1]]$id
[1] 3265366675164236800
```

As you noted before, the ID should be `3265366675164236880` where the last two digits are different.

**Comment by fawda123** [comment]
@mkiang try it now, I added a dependency to jsonlite that will parse large integers from JSON responses as character strings.

**Comment by mkiang** [comment]
Confirmed that did the trick. Thanks again for your work on this!

**Comment by fawda123** [comment]
Cool, I'll get a new version on CRAN soon.
