### ISSUE TITLE
Add elevation to activity lines in heat maps

### ISSUE THREAD

**Issue by fawda123** [fawda123/rStrava#12]
@padpadpadpad Thought this would be a neat way to look at elevation changes along a ride.

**Comment by fawda123** [comment]
Check it out... 5b3acc5520fb958d4264785af10ca4134a0cd349
```r
# get activities, get activities by location, plot
my_acts <- get_activity_list(stoken)
get_heat_map(my_acts, acts = 2, alpha = 1, add_ele = T, key = mykey, size = 2, col = 'Reds')
```
![unnamed-chunk-8-2](https://cloud.githubusercontent.com/assets/3086881/18555207/a02f8066-7b2c-11e6-99dd-4412cb4d38ab.png)

**Comment by padpadpadpad** [comment]
This looks ace. I think another way to look at it would be % increase. Looking at elevation differences rather than absolute elevation. Will have a play and get back to you.

**Comment by fawda123** [comment]
Yea, I think the issue is that the lat/lon values only define vertices, so one elevation applies to only one straight line.  This is okay for the elevation profile plots because you can draw lines between locations to make elevation continuous but it doesn't work for the heat maps.  You'd have to run an interpolation scheme between locations to fill in more lat/lon values... not impossible just another thing to add.

**Comment by padpadpadpad** [comment]
It seems that my post didn't post (having some internet issues). Yea that would be rather fantastic.

Here is a gradient plot...

![heat_map_with_gradient](https://cloud.githubusercontent.com/assets/10220722/18561403/9eb5957c-7b77-11e6-8e50-126512612686.png)

**Comment by fawda123** [comment]
Nice, I like the gradient approach.  Can you add that as a PR?  We could also set up the color ramp so downhill and uphill are different colors.

**Comment by padpadpadpad** [comment]
I have added it as a pull request already... Yea I think an automatic Spectral colour palette if gradient = TRUE would be the way forward.

**Comment by fawda123** [comment]
Thanks, I'll work on the color ramp tomorrow.

**Comment by padpadpadpad** [comment]
Nice.

For ease of defining which maps to fit it might be easier to use this function on the data frame rather than the downloaded list. Gives easier input for filtering activities for get_heat_map. Be it a heat map of specific activities or a single ride with gradient.

**Comment by fawda123** [comment]
I just added a few new arguments to `get_heat_map`: `expand` for more location points along lines (gets ride of the blocky elevations), `as_grad` as optional argument to plot % gradient instead of elevation, and `maptype` to change the base map downloaded from Google.  

I agree that using the list input for the function makes it a bit more difficult to pull relevant data.  However, I think the way it's set up is useful because it limits the number of steps from download to plotting.  Ultimately, we should have some query function to pull rides from the list by location, date, etc.  Whether this is done on the list or data frame is arbitrary, I guess.
