### ISSUE TITLE
Query function

### ISSUE THREAD

**Issue by fawda123** [fawda123/rStrava#14]
Create a function that searches the activities list (or data frame) by a search criteria - by date, by location, by distance, etc.

**Comment by padpadpadpad** [comment]
I like this idea, but is it not essentially the filter/subset function in the data frame once you've done some manipulations?

And I do understand it gets less steps from download to plotting a map, but if plotting multiple maps in the same session a single download of all your data is surely easier than downloading possibly the same subset of data multiple times...

**Comment by fawda123** [comment]
I agree, I mean subset after download, of course, no sense in downloading for every query.  I'll have to think about this for a bit.  I think there's a way to do this using different S3 methods for lists (raw) and data frames (compiled activities).

**Comment by fawda123** [comment]
I just added some S3 methods for the plotting functions to handle both the raw activity list and the data.frame returned by compile_activities.  4a7916539ca99b7028eb87660ba9c5fb4f14c844

You should be able to use the functions like this now:
```r
 my_acts <- get_activity_list(stoken)

# default
get_heat_map(my_acts, acts = 1, alpha = 1)

# plot elevation on locations, requires key
mykey <- 'Get Google API key'
get_heat_map(my_acts, acts = 1, alpha = 1, key = mykey, add_elev = TRUE, col = 'Spectral', size = 2)

# compile first
my_acts <- compile_activities(my_acts, acts = 1)
get_heat_map(my_acts, key = mykey)
```
Does that make sense and/or work correctly?  The raw data list is now an `actlist` object and I plan on adding a query function to handle it specifically.

**Comment by fawda123** [comment]
Actually, a separate query function is stupid, you're right that working with the data frame of compiled activities is better.  Closing this...
