### ISSUE TITLE
ggmap stretching text

### ISSUE THREAD

**Issue by padpadpadpad** [fawda123/rStrava#16]
So when I use get_heat_map() it stretches the text on the google maps even if I and change the ratio when saving it to a square.

It seems to be the coord_equal() call instead of coord_cartesian(). Cannot work out why your examples are wonderful and square and mine are all rectangle though...

![heat map_recent](https://cloud.githubusercontent.com/assets/10220722/18816975/bf2a258e-834c-11e6-8b4a-53fa5359686d.jpeg)

**Comment by fawda123** [comment]
Hm, that's odd.  I'm getting the problem if I change it to `coord_cartesian()`.  I think it's a ggmap problem, have you tried using `coord_fixed()`?  I think this is the same as `coord_equal()` but might be worth a try.

**Comment by padpadpadpad** [comment]
Nope no good. It is very odd not sure whats going on. Not the greatest work around but I suppose putting a parameter in for type of coord might be useful.

And possibly raising an issue in ggmap?

**Comment by fawda123** [comment]
You can just add it to the end of the function like this:
```r
get_heat_map(my_acts, acts = 1193, key = mykey, alpha = 0.8, size = 1, f = 0) + 
  ggplot2::coord_cartesian()
```
Is that okay or should it be added as an argument?

**Comment by padpadpadpad** [comment]
That'd be fine for me.
