### ISSUE TITLE
get_elev_prof error

### ISSUE THREAD

**Issue by cassiel74** [fawda123/rStrava#17]
Hi,
I got this error when using  get_elev_prof
`Error in eval(expr, envir, enclos) : object 'location_city' not found`

**Comment by fawda123** [comment]
@cassiel74 Try downloading the package again and re-running.  I removed an unnecessary selection of that column.   6689da0580b77e83ce7142b5f02f84e933c181d9

**Comment by cassiel74** [comment]
It works now.
