### ISSUE TITLE
Remote rStrava

### ISSUE THREAD

**Issue by cassiel74** [fawda123/rStrava#19]
Not really an issue but something really close to.

I played around with rStrava an developed a script which produces an rmarkdown html file with plots of performances on my favourite segments. I pushed all the stuff in a git repo on a remote server hence no DE and connection with terminal

Running the script:
```
> source('token.R')
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
```

Of course the auth process never ends...
Is there any workaround?

**Comment by fawda123** [comment]
Yea I remember having a similar issue a while back.  To be honest I'm not terribly familiar with authentication protocols, maybe @padpadpadpad or @ptdrow can help.

**Comment by fawda123** [comment]
I also suggest posting [here](https://github.com/hadley/httr/issues) since this is really an httr issue.
