### ISSUE TITLE
api help

### ISSUE THREAD

**Issue by cjlortie** [fawda123/rStrava#20]
hi there,
I want to scrape my strava data. I set up profile, got appname, client id, and app secret.
However, what I get to stoken step, it says enter authorization code. How do I get that?
In strava, I made up application name but what website and authorization callback domain do I list to get the authorization code?  I just put the github repo I want to work in but that does not work. sorry for asking.

**Comment by cjlortie** [comment]
maybe it does not matter.
when I view 'my strava api' panel, I see client ID, client secret, and your access token. I assume these match to app_client_id, app_secret, and then when I run stoken and it asks for authorization code in console I put the access token from strava api panel.

however, I do this and get the following error:
Error in init_oauth2.0(self$endpoint, self$app, scope = self$params$scope,  : 
  Unauthorized (HTTP 401). Failed to get an access token.

**Comment by fawda123** [comment]
@cjlortie Here's how I have mine setup: 

```r
library(rStrava)
library(httr)
library(httpuv)

strava_token <- strava_oauth(app_name, app_client_id, app_secret, app_scope = 'public', cache = TRUE)
stoken <- config(token = strava_token)
myinfo <- get_athlete(stoken, id = '2837007')
```

The three arguments that are entered in `strava_oauth` are from the Strava API on your personal account.  The screenshots below show where each can be found on the API.  
![capture](https://cloud.githubusercontent.com/assets/3086881/20350766/c24f8d60-abd5-11e6-96ce-d717b74d0c29.PNG)
![capture2](https://cloud.githubusercontent.com/assets/3086881/20350772/c62fc31e-abd5-11e6-8137-683c4f04a87d.PNG)
You may have to authorize the app outside of R by clicking on the link right above the app name.  Does that help?

**Comment by crickles** [comment]
Hi, Your workflow appears to log onto Strava with the credentials of the app creator. Do you also support / have sample code for throwing a page for users other than the app creator to grant the app access to their data? Thanks!

**Comment by fawda123** [comment]
@crickles yea you need to create a Strava account and create your own API. There should be enough info [here](https://strava.github.io/api/#access)
