### ISSUE TITLE
Heat Map error

### ISSUE THREAD

**Issue by regdunlop** [fawda123/rStrava#22]
I'm trying to duplicate your examples using my own strava API and account / data.
Everything works fine until I try to generate the heat map.
When I run this chunk of code:

my_acts <- get_activity_list(stoken)
acts <- lapply(my_acts, function(x) x$location_city) %in% c('Calgary') 
get_heat_map(my_acts, acts = which(acts), col = 'darkgreen', size = 2, dist = F)

I'm getting the following error code:

Error in stats::approx(x = x$lon, n = expand * nrow(x)) : 
  need at least two non-NA values to interpolate

Any thoughts on what I'm doing wrong here?

**Comment by fawda123** [comment]
Is your activity list downloading correctly (does `my_acts` have information)?

**Comment by regdunlop** [comment]
Yes, it seems to be downloading correctly.  
I'm seeing:
my_acts  (Large list 1115 elements, 8Mb)
and then a long list of elements including things like distance, moving time, start date etc

**Comment by fawda123** [comment]
Okay, that's good, I was afraid it wasn't getting the data correctly.   Next question.... does the vector `acts` include data (T/F value for each element in `my_acts`)?

This would be easier to troubleshoot if I could use your data.  Anyway you can put it on GitHub?
