### ISSUE TITLE
API functions (token) - Strava oauth issue.

### ISSUE THREAD

**Issue by Fazmin** [fawda123/rStrava#24]
I'm trying to use this with a strava token. I've followed the instructions and got an app_client _id, app_secret.

app_name <- 'myappname'
app_client_id  <- 'myid'
app_secret <- 'xxxxxxxx'

although when try to create the authentication token. i see this error on the console.
stoken <- httr::config(token = strava_oauth(app_name, app_client_id, app_secret))

oauth_listener() needs an interactive environment.
Any idea how to resolve this? Thank you.

**Comment by fawda123** [comment]
Have you tried:

`stoken <- httr::config(token = strava_oauth(app_name, app_client_id, app_secret, cache = TRUE))`

If so, do you see `.httr-oauth` in your workspace?  

Also, can you paste your `sessionInfo()`?

**Comment by Fazmin** [comment]
Thank you so much for getting back to me. the app just crashes before it outputs anything to the seessionInfo and I don't have a .httr-oath file in my workspace either. 

But I have the error below on the console.

````
Warning: replacing previous import by magrittr::%>% when loading "rStrava"
Warning: Error in : oauth_listener() needs an interactive environment.
Stack trace (innermost first):
    52: oauth_listener
    51: init_oauth2.0
    50: self$init_credentials
    49: .subset2(public_bind_env, "initialize")
    48: Token2.0$new
    47: oauth2.0_token
    46: strava_oauth
    45: structure
    44: request
    43: httr::config
    42: server [/srv/shiny-server/rserver/StravaTools/istrava/server.R#14]
     1: runApp
Error : oauth_listener() needs an interactive environment.

shiny-server-client.min.js:1 The application unexpectedly exited.
```

I'm running the shiny server on a separate port which is not open to public is that an issue for the rStrava token authentication?

**Comment by fawda123** [comment]
I'm not an expert in authentication protocol, but it might be the private port.  Maybe try getting the `.httr-oauth` file outside of the app (i.e., just use the package functions as in the [readme](https://github.com/fawda123/rStrava/blob/master/README.md) file), then save the file to the home directory when running the app.  You should get authorization with the token from a cached file like this: 

`stoken <- httr::config(token = readRDS('.httr-oauth')[[1]])`

Seems like authorizing on the fly within a Shiny application is an issue.
