### ISSUE TITLE
Issue plotting elevation

### ISSUE THREAD

**Issue by ryanheitsmith** [fawda123/rStrava#26]
I'm trying to work through your examples and am getting an error whenever I try to use elevation information from the googlemaps api.

`# plot elevation along a single ride
get_heat_map(my_acts, acts = 1, alpha = 1, add_elev = T, f = 0.1, key = mykey, size = 2, col = 'Spectral', maptype = 'satellite', units = 'imperial')`

The above piece of code is giving me the following error

> Error in data.frame(..., check.names = FALSE) : arguments imply differing number of rows: 1190, 0

I get the same error with the get_elev_prof() function. Any insight would be appreciated.

**Comment by fawda123** [comment]
Does `mykey` return the correct character string for your Google API key?  This is an obscure error that gets returned by rStrava if the elevation data are not retrieved from `rgbif::elevation`.  Try running this with your key.  You'll need another key if it doesn't work.

```r
library(rgbif)
# mykey <- 'enteryourAPIkeyhere'
key <- name_suggest('Puma concolor')$key[1]
dat <- occ_search(taxonKey=key, return='data', limit=300,
  hasCoordinate=TRUE)
elevation(latitude=dat$decimalLatitude, longitude=dat$decimalLongitude,
  key = mykey)
```

**Comment by fawda123** [comment]
161d957c4a1c8b05bae28ef8e96677a8328a0e26 More informative error message added.
