### ISSUE TITLE
Adding some extra functions

### ISSUE THREAD

**Issue by padpadpadpad** [fawda123/rStrava#27]
Hi Marcus

Long time no work on this for me! 

Just thought I would give you a heads up that I am hoping to add a few extra bits of functionality in the next few weeks.

- Am working on returning the speed_splits as a data frame for multiple activities as something like get_all_laps()
- changed get_dists() to allow a different column name to be used to split the data. Think this might be ridiculous functionality as a group_by() %>% mutate(distance = get_dists()) for a single level would work.
- compile_segment() for cleaning up the output of get_segment()

I like the way you code with methods and get_act_frames() for writing a function within your function. Any tips for using that method as may save you a job of cleaning up my messier code!

Am essentially trying to grab all the parkrun segments and try visualise which one is hardest based on total elevation and what not and try produce a few nice plots.

Have already got a couple of these ready!
Cheers
Dan

**Comment by fawda123** [comment]
Hi Dan, sorry for not getting back to you sooner, been switching jobs.  That all sounds good, I just created a development branch you can use for these new functions.  We can merge them with the master when we're happy with the changes. 

Thanks,

Marcus

**Comment by padpadpadpad** [comment]
Hi Marcus

This has been put to the bottom of a big pile of things for a while now. But I have implemented a bunch of changes and I think everything still works as it was just with loads more functionality.

There has been quite a lot of stuff on Twitter in the last few months about people plotting their Strava data in R using [strava](https://github.com/marcusvolz/strava) package. I am hoping to do a few blogs about rStrava this year as it can do some really cool stuff.

As I am a GitHub novice do I try and send a PR request to my branch of this repository? And then you merge branches?

Looking to add a few tests in as well to make sure everything works. Would this be better to do all in one PR or afterwards?

Also I started making a [Shiny app](https://padpadpadpad.shinyapps.io/parkruns/) trying to judge the most difficult parkrun in the UK. Used rStrava to get segment data on each parkrun (I have only manually found half of the ids so far). 

Bit of a rambling comment
Cheers
Dan

**Comment by fawda123** [comment]
Hi Dan, 

Yes, you can make a pull request to the development branch.  You'll have the option to pick a branch when you make the request.  Feel free to send it all in one go, but if you could, can you just write a few sentences in the request about what the pull includes (new functions to do xyz, etc.)?  

I've also been following the recent buzz about the strava package.  Pretty cool stuff.  If you like, I can  help co-author a blog highlighting our package.  I've got a blog (which I haven't posted to in a while) that's hooked in to R-bloggers.  We could post there and I can give you author credit.  Whatever you prefer. 

Cheers, 

Marcus

**Comment by fawda123** [comment]
Sorry, just saw you already made the PR.  I'll have a look.

**Comment by fawda123** [comment]
The function `plot_spdsplits` works fine for one activity, but I'm not getting anything from the example in `get_spdsplits`. I get an empty data.frame/tibble.  I assume this isn't what you intended?

```r
# get my activities
stoken <- httr::config(token = strava_oauth(app_name, app_client_id, app_secret, cache = TRUE))
my_acts <- get_activity_list(stoken)

# get spdsplits for all rides
spd_splits <- purrr::map_df(my_acts$id, get_spdsplits, stoken = stoken, units = 'metric', .id = 'id')
```
returns:
```r
# A tibble: 0 x 0
```

**Comment by padpadpadpad** [comment]
Hi Marcus

Sorry about this, the function works on the compiled activities rather than the big nested list. So the error is just because I haven't put a `MyActs <- compile_activities(my_acts)` in the example. Should be:

``` r
# get my activities
stoken <- httr::config(token = strava_oauth(app_name, app_client_id, app_secret, cache = TRUE))
my_acts <- get_activity_list(stoken)

# compile activities
MyActs <- compile_activities(my_acts)

# get spdsplits for most recent 2 activities
spd_splits <- purrr::map_df(MyActs$id[1:2], get_spdsplits, stoken = stoken, units = 'metric', .id = 'id')

```

Can do a PR request later today.
