### ISSUE TITLE
athlete's activity 

### ISSUE THREAD

**Issue by Okinur** [fawda123/rStrava#28]
Is it possible to download a specific athlete's activity list like `get_activity_list(stoken)` but  for another person who is not authenticated)?
Because I try using the command get_activity_list(stoken, id = 'athlete_id') but (correctly) I do not get the activity list of that athlete but the activity whose id coincides with the athlete_id.
Is it possible?
Thanks a lot

**Comment by fawda123** [comment]
@Okinur I don't think this is possible, the Strava API is setup to allow access only to your activities.
