### ISSUE TITLE
Problem with pagination requests with the leaderboards

### ISSUE THREAD

**Issue by ptdrow** [fawda123/rStrava#3]
When you request for several pages of the leaderboard the `get_leaderboard` function retrieves only the first one. The problem is in the `get_pages` verification of the "last page":

`if(length(content(req)) < per_page) {break}`

The problem is that for the leaderboard the result of `length(content(req)` is 5 and not the number of athletes retrieved.

This is a problem that I've seen only with this request. With the efforts (`get_efforts_list`) it works.

**Comment by fawda123** [comment]
@ptdrow What about this?   6e6b759e426709aa1e238ce137741273322291cc

**Comment by fawda123** [comment]
@ptdrow Fixed aba35b2555ff00ba9d1355f3f3844fc91ef1ad64
