### ISSUE TITLE
Contributing with compile_streams

### ISSUE THREAD

**Issue by lgaborini** [fawda123/rStrava#32]
Hello!   
I wanted to contribute with some functions to extract all streams (time, distance, latitude, longitude, elevation, heart rate, ...) for an activity, and compile them to a nice tidy data frame:

``` r
all.stream.types <- list("time", "latlng", "distance", "altitude", "velocity_smooth", "heartrate", "cadence", "watts", "temp", "moving", "grade_smooth")

stream.left <- get_streams(stoken, id = id.left, types= all.stream.types, resolution = 'high')

compile_stream(stream.left, id = 1159843375)
#> # A tibble: 1,614 x 12
#>    altitude cadence distance grade_smooth heartrate moving  temp  time velocity_smooth   lat   lng         id
#>       <dbl>   <int>    <dbl>        <dbl>     <int> <lgl>  <int> <int>           <dbl> <dbl> <dbl>      <int>
#>  1    1323       59      1.2        -13          78 FALSE     25     0             0    46.4  7.16 1159843375
#>  2    1323.      59      2.5        -11          78 TRUE      25     1             1.3  46.4  7.16 1159843375
#>  3    1322.      59      6.2         -8.2        81 TRUE      25     4             1.3  46.4  7.16 1159843375
#>  4    1322       64      8.9        -11          84 TRUE      25     7             1.1  46.4  7.16 1159843375
#>  5    1322       64     10.3         -3.8        86 TRUE      25     8             1.1  46.4  7.16 1159843375
#>  6    1322       64     13.4         -1.9        90 TRUE      25    10             1.2  46.4  7.16 1159843375
#>  7    1322       76     16.6         -5.8        92 TRUE      25    11             1.5  46.4  7.16 1159843375
#>  8    1322.      77     19.4        -10.6        94 TRUE      25    12             2.1  46.4  7.16 1159843375
#>  9    1321.      78     24          -13.2        97 TRUE      25    14             2.3  46.4  7.16 1159843375
#> 10    1321.      79     26.6        -14.2        98 TRUE      25    15             2.6  46.4  7.16 1159843375
# ... with 1,604 more rows
```

It should also be possible to deal with multiple activities at once.

My code is working, but how should I integrate it with the current project?

Judging by the current code base, the main function should be then called `compile_streams`, as it builds a data frame from the output of `get_streams` (i.e. a StreamSet). 

However, to simplify the usage, the call to `get_streams` could be hidden from the user.    
The resulting function should then operate directly on the activities: grab the desired activity ids, grab the streams for each activity, compile each StreamSet to a data frame using `compile_stream`, and concatenate the results.    
This is much more user friendly, but slightly violates the `compile_*` convention. Also, it would be desirable to cache the streams somewhere.

I could also base it on the output of `compile_activities`. This should also give us the advantage to be able to automatically deal with the units, yet it is no longer a `compile_*`

What do you suggest to do?

**Comment by fawda123** [comment]
@lgaborini that's a cool function, thanks for sharing.  I agree it would be best to get the results with one function as seen by the user.  

Consider putting the `compile_streams` function as a call within `get_streams`, so the user doesn't have to call it themselves.  Still include `compile_streams` as it's own function, just don't export it to the namespace.  You could set it up to compile all activities within `get_streams` so the dataset that is returned includes multiple activities (with a column for the unique activity id).  Then the user can just filter the resulting dataset themselves (e.g., `filter(stream.left, id = 1159843375)`).  

Does that make sense?  I can try to help if you want to submit a pull request.

**Comment by lgaborini** [comment]
Submitted the PR!

Apparently, one can also retrieve streams for a segment rather than an activity.    
This is described by the API, so I precised that this function only retrieves **activity** streams.

However, I was not able to retrieve segment streams playing with the API using `get_streams`. Maybe I will fix that up in the future.
