### ISSUE TITLE
Instructions for API Functions out of date?

### ISSUE THREAD

**Issue by jzadra** [fawda123/rStrava#35]
It seems that Strava may have changed the [API setup page](https://www.strava.com/settings/api) since the [API Functions (token)](https://github.com/fawda123/rStrava#api-functions-token) instructions were written.  There is no field for clientid or secret.  Rather, they are asking for Club, Website, Application Description, and Authorization Callback Domain

**Comment by jzadra** [comment]
Thanks.  I figured it out,  I was just suggesting to update the instructions to reflect the new new method.

**Comment by fawda123** [comment]
@jzadra What exactly has changed?  As far as I can tell, the documentation is the same.
