### ISSUE TITLE
update functions that use google api and external dist ests with streams data

### ISSUE THREAD

**Issue by fawda123** [fawda123/rStrava#36]
No need to get elevation from google or to estimate distances in some of the plot functions (e.g., `get_heat_map`).  Info from `get_streams_activities` can be used directly.  Update the functions to remove redundancies...

#32

**Comment by fawda123** [comment]
@padpadpadpad is this something you'd be interested in handling?  The functions added by @lgaborini get elevation and distance direct from the API.

**Comment by padpadpadpad** [comment]
Yes I would be able to give it a go. Does `get_stream_activities()` directly link with the output of `compile_activities()`? Possibly through the `upload_id`?

**Comment by fawda123** [comment]
Yea, `get_stream_activities` can work with the activity list from `get_activity_list` or the `actframe` object returned by `compile_activities`.  The `acts` argument form `get_stream_activities` is an index value to link with the `upload_id`.  I would also look at the `get_streams` function - it works under the hood of `get_stream_activities` to pull each `upload_id`.

**Comment by fawda123** [comment]
I retained the Google API elevation features, I think this works quicker for retrieving elevation of individual activities from an `actframe` object.  Instead I just made some S3 methods for the plotting functions that work with `strframe` objects.  d70a353f12c7a366c150786a2e6963ca29b8afc9 258079ff6041550b53cd6e8a99af761cf10ecd4b
