### ISSUE TITLE
Troubleshooting token errors?

### ISSUE THREAD

**Issue by jzadra** [fawda123/rStrava#37]
Every attempt I've made to get the stoken results in:

`{"message":"Bad Request","errors":[{"resource":"Application","field":"redirect_uri","code":"invalid"}]}`

Are there any troubleshooting instructions?

**Comment by fawda123** [comment]
Does this code create a .httr-oauth file in your working directory?

```r
# create the authentication token
stoken <- httr::config(token = strava_oauth(app_name, app_client_id, app_secret, cache = T))
```
