### ISSUE TITLE
Error while installing Rstrava

### ISSUE THREAD

**Issue by loganteal** [fawda123/rStrava#38]
I get the error below, I have already installed Rcpp

* installing *source* package 'rStrava' ...
** R
** preparing package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'Rcpp'
ERROR: lazy loading failed for package 'rStrava'

**Comment by fawda123** [comment]
Have you tried installing the Rcpp package first?
