### ISSUE TITLE
Authenticating other users

### ISSUE THREAD

**Issue by mtengelin** [fawda123/rStrava#39]
Hello, love the rStrava package! 

I'm building a Shiny app to plot and download all my activities, and it works fine. But I'm struggling to make it available for other users, basically how to use the strava_oauth function on R Shiny so that any user can authorise my app to access his/her data. I am trying the below, but it only works locally in R but not once the R Shiny app is published:
stoken <- httr::config(token = strava_oauth(app_name, app_client_id, app_secret, app_scope = "view_private", cache=FALSE))
I am also using "authorization callback domain" as "localhost" for the app on Strava.com, don't know if that's correct or if I should use something else.

Thanks!

**Comment by fawda123** [comment]
Yea I don't think the Strava API is setup to do this.  As far as I know, the Strava app created by a single user can only be used to access their data.  Maybe you can setup a Shiny app to let others enter their own stoken info to access their individual info - assuming people would be okay with this.  I'm not even sure this is feasible though.

**Comment by niklasvm** [comment]
@mtengelin I have created a functioning shiny app that allows users to authenticate and give the required permissions. (available at https://niklasvm.shinyapps.io/Strava_Route_Map/) This was about 18 months ago so I would need to dig up the code. I will find it and post the steps here.

**Comment by mtengelin** [comment]
That's great @niklasvm, exactly what I was hoping to do. Would love to see the code if you can find it!

Thanks!

**Comment by mtengelin** [comment]
Thanks very much for this @niklasvm, really appreciated! I gave it a try with a script that attempts to authenticate a user and then letting him download all his activities (see attached). Do you understand what the problem is? Note that I wasn't sure how to use the appURL function so I hardcoded the url.

//Martin
[app.R.txt](https://github.com/fawda123/rStrava/files/2121131/app.R.txt)

**Comment by fawda123** [comment]
@niklasvm I definitely think the app will be used but it's outside of the scope of the package (i.e, app vs package).  Perhaps we could include some functions (not exported) that help with the app, then provide a link on the README?

**Comment by niklasvm** [comment]
@mtengelin do you get a particular error message?

**Comment by niklasvm** [comment]
hey @mtengelin. I've managed to get it working (i get a csv containing all my activities). I have made the following changes:

1. reference ```jsonlite``` and ```httr``` at the beginning. These are required for some of the steps.
1. The application link needs to be built dynamically so that you can run it from both a local and shinyapps context. I generate the link using a ```uiOutput linked``` to ```output$authUI```.
1. I have added the ```session``` parameter to the server function
1. I have added the ```appURL()``` function


Full code:

```{r}
# Libraries
library(rStrava)
library(jsonlite)
library(httr)

# Strava API info
app_name <- '' # chosen by user
app_client_id  <- '' # an integer, assigned by Strava
app_secret <- '' # an alphanumeric secret, assigned by Strava
app_url <- "http://tengelin.shinyapps.io/StravaDownload"


# Define the UI
ui <- fluidPage(
  uiOutput('authUI'),
  br(),
  textOutput('auth_success'),
  downloadLink('downloadData', 'Download all activities')
)


# Define the server code
server <- function(input, output,session) {
  
  appURL <- reactive({
    
    if (!is.null(session)) {
      app_url <- paste0(session$clientData$url_protocol,
                        "//",
                        session$clientData$url_hostname, 
                        ifelse(
                          session$clientData$url_hostname == "127.0.0.1", 
                          ":",
                          session$clientData$url_pathname
                        ),
                        session$clientData$url_port
      )
      return(app_url)
    }
  })
  
  # Generate authentication link
  authURL <- reactive({
    paste('https://www.strava.com/oauth/authorize?','client_id=',app_client_id,'&response_type=code&redirect_uri=',appURL(),'&approval_prompt=auto&state=',sep='',collapse='')
  })
  
  # Parse out the authentication code from the url
  authCode <- reactive({
    pars <- parseQueryString(session$clientData$url_search) 
    if(length(pars$code) > 0){
      return(pars$code)
    } else {
      return(NULL)
    } 
  })
  
  # Get stoken
  get_stoken <- reactive({
    code <- authCode()
    response <- RCurl::postForm('https://www.strava.com/oauth/token',
                                client_id = app_client_id,
                                client_secret = app_secret,
                                code = authCode())
    cat(response)
    token_data <- fromJSON(response)
    accesstoken <- token_data$access_token
    stoken <- add_headers(Authorization = paste0("Bearer ",accesstoken))
    return(stoken)
  })
  
  output$authUI <- renderUI({
    if (is.null(authCode())) {
      a('Click to authorise Strava Access',href=authURL())
    }
  })
  
  # Download data
  output$downloadData <- downloadHandler(
    filename = function() {
      paste('StravaActivities-', Sys.Date(), '.csv', sep='')
    },
    content = function(con) {
      # get and save all activities
      my_acts <- get_activity_list(get_stoken())
      
      # Convert activities list to data frame
      my_acts.df <- compile_activities(my_acts, acts = NULL, units = "metric")
      
      write.csv(my_acts.df, con, row.names = FALSE)
    }
  )
}

# Return a Shiny app object
shinyApp(ui = ui, server = server)
```


Easiest is for you to use git to view the exact changes.

Regards
Niklas

**Comment by mtengelin** [comment]
Wow, that's very kind of you, thanks a lot Niklas! I'll try it out and let you know.

**Comment by fawda123** [comment]
@mtengelin @niklasvm Thanks guys, this is great stuff.  Let me know if I can help with anything.  Here's what I'm thinking:

* Include additional plotting features provided by rStrava, e.g., `get_heat_map`, `get_elev_prof`, and/or `get_spdsplits`
* We also have some new functions thanks to @lgaborini that pull stream data (precise, time, distance, speed, etc. for individual activities).  These could be incorporated in the app and/or plotted with ggplot. 
* Host the app and put a link on the readme.  It would be good to create a separate repo for the app source code in case anyone wants to fork/update.   

Thoughts?

**Comment by fawda123** [comment]
Sounds good, I'll keep an eye on the new repo.  I can add some of the other plot functions once it's built out a bit. Thanks!

**Comment by mtengelin** [comment]
Thanks guys, this is great!

Niklas, what's the global.R file you are sourcing? It's not in the repo.

//Martin

**Comment by niklasvm** [comment]
Apologies, forgot to add it. Its there now.

**Comment by mtengelin** [comment]
Niklas, I get the following error when I try to run your app:
"Downloading activities...
Warning: Error in strsplit: non-character argument"

And when I click on the authorise link I get this:
"{"message":"Bad
Request","errors":[{"resource":"Application","field":"client_id","code":"invalid"}]}"

Any idea why? Something I'm doing wrong?

//Martin

**Comment by niklasvm** [comment]
I will have a look at it and let you know

**Comment by niklasvm** [comment]
@mtengelin I've pushed some changes and updated the readme. It should work now

**Comment by mtengelin** [comment]
Brilliant Niklas, works well now. Thanks!
