### ISSUE TITLE
Error in get_pages when using get_segment and get_leaderboard

### ISSUE THREAD

**Issue by padpadpadpad** [fawda123/rStrava#4]
Hi. Awesome package. 

I get this error when starting a script with a get_segment request.

"Error in get_pages(url_segment(id, request = "all_efforts"), stoken, queries = queries,  : 
  object 'usage_left' not found"

However when I randomly pull other bits of strava data using other commands the error eventually goes away. Is there a way to define the amount of usage for the first command I wonder?

Cheers
Dan

**Comment by fawda123** [comment]
@padpadpadpad The `usage_left` variable is created by the package to show the number of requests left for the current API session.  I found a bug in the `get_pages` function that might have been the issue, try reinstalling and let me know if you still have problems. 

Alternatively, you can just define usage left like this, though the functions should do this automatically:
`usage_left <- as.integer(c(600, 30000))`

**Comment by padpadpadpad** [comment]
@fawda123 your patch fixed it. I was overriding it by using `usage_left <- Inf` before my first function call.

Thanks for the fix.
Dan
