### ISSUE TITLE
strava_oauth

### ISSUE THREAD

**Issue by bnwicks** [fawda123/rStrava#43]
Running "strava_oauth"; authenticates and returns in the web browser;
> Authentication complete. Please close this page and return to R.

But R is returning;
> Waiting for authentication in browser...
> Press Esc/Ctrl + C to abort
> Authentication complete.
> Error in oauth2.0_access_token(endpoint, app, code = code, user_params = user_params,  : 
>   Unauthorized (HTTP 401). Failed to get an access token.

Have you encountered this before?

**Comment by fawda123** [comment]
Hi @bnwicks I've seen that before.  Does it still pop up if you cache your authentication credentials?

**Comment by bnwicks** [comment]
Thanks Marcus,

Seems to be an issue with httr, though it's somewhat intermittent. It's
documented here;
https://github.com/r-lib/httr/pull/485

I have a cached token working now, so all good.

**Comment by bnwicks** [comment]
Most times. I've had it work and not work (an improvement on not working).

**Comment by fawda123** [comment]
Okay thanks, at least it's documented here in case others have the same issue.

**Comment by ries9112** [comment]
I ran into this same problem today. Installing the dev version of httr did not work for me and I was unable to resolve the issue looking through the linked thread. Thoughts on how to fix this and get a token to cache?

**Comment by fawda123** [comment]
@bnwicks did you ever solve this issue?

**Comment by piercefa** [comment]
I am having the same problem
