### ISSUE TITLE
Add the description of an activity

### ISSUE THREAD

**Issue by olangfor** [fawda123/rStrava#44]
Hi,

Firstly, thank you for this R package.  Very helpful and useful for my training.

I'm trying to extract the description on an activity, but I am unable to locate it in the activity list object.  I can see that the Strava API has the description field in their API.  Would it be possible to add it here?

Sorry if it already exists.  If it does, please could you let me know.

Kind regards,

Oliver

**Comment by niklasvm** [comment]
Hi Oliver

It doesn't look like description is one of the values returned in the activity list object if you look at: https://developers.strava.com/docs/reference/#api-Activities-getLoggedInAthleteActivities

You can use:
```{r}
activity_id <- xxxxxx
dd <- get_activity(activity_id,stoken)

print(dd$description)
```

**Comment by olangfor** [comment]
Perfect.  Thank you very much.
