### ISSUE TITLE
get_heat_map(): Error in while (vindex < vlen) { : missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by jzadra** [fawda123/rStrava#45]
I"m getting an error I can't track down.  I"m able to get the data and compile:

`my_acts <- get_activity_list(stoken)`

`act_data <- compile_activities(my_acts)`

But then when I try to do the heat map, I get the following error:

`get_heat_map(act_data)`
`Error in while (vindex < vlen) { : missing value where TRUE/FALSE needed`

**Comment by fawda123** [comment]
Okay, I just found out that unfortunately Google has updated its maps API which is used by `get_heat_map`.  You'll have to get a key from Google and register it using the dev version of ggmap, see the announcement on the readme: https://github.com/dkahle/ggmap

We'll have to update the documentation for `get_heat_map` to include this extra step.  The function works as intended when I tried it with my activities, but let me know if you still have problems.

```{r}
# get dev version of ggmap, register key after you get it
devtools::install_github("dkahle/ggmap", ref = "tidyup")
library(ggmap)
register_google('xxxxxxxxxxx') # enter your key here

# should work now
library(rStrava)
my_acts <- get_activity_list(stoken)
act_data <- compile_activities(my_acts)
get_heat_map(act_data)
```

**Comment by baslat** [comment]
I'm getting the same errror, even after registering my gmaps API key. I get the same error when calling `get_elev_prof()`

**Comment by fawda123** [comment]
Okay, finally figured out what the problem was.  There are some activities without geographic information, such as those that are entered manually.  There's a new function (`chk_nopolyline()`) that checks for and removes these activities if trying to use `get_heat_map()` or `get_elev_prof()` for these activities.  

b40d4b064c30b0bb897a7fb331160455fa2322d7
