### ISSUE TITLE
Existing athletes not found with `athl_fun`

### ISSUE THREAD

**Issue by fawda123** [fawda123/rStrava#49]
Hi Marcus, I have been having issues with the function athl_fun() too, however my error says that the "Athlete does not exist":

```
> athl_fun(3354405)
3354405 1 of 1 
Error in athlind_fun(val) : Athlete does not exist
$`3354405`
[1] NA
```

The URL for this athlete is https://www.strava.com/athletes/3354405 and the profile is public (i.e. I can see the stats).

I updated the rStrava package after you made the changes but the issue persists. Any ideas how to solve this?

Many thanks!

**Comment by fawda123** [comment]
There was some issue with `RCurl::url.exists()` where `FALSE` was being returned even though the page exists.  So I just removed this check for ease of use at the risk of returning a less than clear error if the page doesn't actually exist. I've noticed that the `athl_fun()` function has become more temperamental with what I guess are updates to Strava's web page.

fea9123e6ceaaad9a7a63e5335a908fa27d6fe12

**Comment by fawda123** [comment]
Yea these are the worst kinds of bugs to track down... @mtengelin is the behavior the same if you are logged in to the Strava website?

**Comment by mtengelin** [comment]
I know... :( If you by logged in mean creating the stoken first, then yes I get the same problem (see below).

Note that I have version 0.16 of the rStrava package. I have another computer with 0.17, but there I get the "Error in athlind_fun(val) : Athlete does not exist" error for all the athletes.

> stoken <- httr::config(token = strava_oauth(strava_app_name, strava_app_client_id, strava_app_secret))
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
> Athletes <- c(1837688, 12767051, 12762229, 25723993, 16473726, 2676921)
> names(Athletes) <- c("Martin", "Steve", "Matteo", "Ravi", "Adrien", "DJ")
> data.df <- athl_fun(Athletes, trace = TRUE)
1837688 1 of 6 
Error in strsplit(cmo, "\\n")[[1]] : subscript out of bounds
12767051 2 of 6 
12762229 3 of 6 
Error in strsplit(cmo, "\\n")[[1]] : subscript out of bounds
25723993 4 of 6 
16473726 5 of 6 
2676921 6 of 6

**Comment by fawda123** [comment]
Okay, the second to last commit fixed the issue with the check for an athlete existing.  Did you reinstall the latest version (sorry about the version updates, they don't always coincide with commits)?

For the logged in issue I mentioned above, I meant if you were logged in on the actual Strava website in the web browser, unrelated to the token.  I've noticed that I get different information for some athletes depending on if I'm logged in or not.  For athlete 16473726, I see this page when I access in a browser if I'm not logged in: 
![image](https://user-images.githubusercontent.com/3086881/51261339-e58a9780-1964-11e9-9d7c-01389c8acb52.png)
But then, after I log in, I see this: 
![image](https://user-images.githubusercontent.com/3086881/51261406-06eb8380-1965-11e9-8c53-ce21f2038fe9.png)
The content at the bottom is what the function should be scraping and it's frustrating that I'm only seeing that after I log in, since the function was developed specifically to eliminate the need for a login and/or token.

**Comment by mtengelin** [comment]
Ok, I've downloaded the latest package and will try a bit being logged in to my browser.

Thanks!

**Comment by alapedriza1** [comment]
Hi Marcus,

I can confirm that after your last commit, the package works and I haven't experienced the 'Athlete does not exist' error anymore.

Many thanks for your work!
