### ISSUE TITLE
Country allocation is wrong

### ISSUE THREAD

**Issue by mtengelin** [fawda123/rStrava#50]
Hello Marcus,

One more issue I've noticed today. When exporting my activities with the get_activity_list() and compile_activities() functions, some activities don't show the correct "location_country". For example, this activity was in Austin, TX but the "location_country" is Switzerland (where I live): https://www.strava.com/activities/1947662478

Actually, many more activities that are in e.g. France, Sweden etc also have Switzerland as country.

Thanks for looking into this if you can.

//Martin

**Comment by fawda123** [comment]
Hm, that's a weird one.  Do you think this is an issue downloading the data from the website or something that gets munged up when the data are compiled with the package?  I just checked all my activities and they are all in the correct country, but my geographic situation is US biased.  

What happens when you compile only the offending activities, for example, if the first five in my list were "wrong"?  Are the countries still mislabelled? 
```r
my_acts <- get_activity_list(stoken)
act_data <- compile_activities(my_acts, acts = c(1:5), units = 'metric')
```

**Comment by fawda123** [comment]
Also, I just modified `get_activity_list()` to retrieve individual activities with the `id` value (you can find the id number in the compiled activity list using the old way of getting all activities).  This functionality was supposed to already be included... but you can use this to see if pulling an individual activity from the API has an incorrect country location.  Make sure to reinstall rStrava from GitHub first before doing this. 

e386685054e86e119a68cef46f260a5d18859e9b

```r
my_acts <- get_activity_list(stoken, id = "2102284746")
my_acts[[1]]$location_country
```

**Comment by mtengelin** [comment]
Thanks Marcus! I tried pulling one activity with the updated function, and indeed the location_country is incorrectly showing "Switzerland" when the activity is recorded in the US (Austin, TX).

> my_acts <- get_activity_list(stoken, id = "1947662478")
> my_acts[[1]]$location_country
[1] "Switzerland"

**Comment by fawda123** [comment]
Ok, try this one.  I pulled out the core functions for making a request to the Strava API.  Just feed it your stoken and change the last part of the URL with the appropriate activity ID.  If you still see the wrong country, it's probably an issue with the API.  An additional test would be to try a request to the API not through R (through Python maybe?).  Or maybe get in touch with Strava to see what's up?  

```r
url <- 'https://www.strava.com/api/v3/activities/2109055140'
req <- httr::GET(url, stoken)
httr::content(req)
```

**Comment by mtengelin** [comment]
Thanks, I still get Switzerland for my US activity. Probably something on the Strava API side, since I tend to get Switzerland (my home country) for many activities that are not in Switzerland, and you mentioned you have US for most activities (which I assume is your home country).

I'll try to contact Strava to see what they say. And will revert back on this thread if I get an answer.

**Comment by fawda123** [comment]
Okay, I also tried to find the activity country directly on the website, but I think that info may only be available through the API.
