### ISSUE TITLE
Export GPX

### ISSUE THREAD

**Issue by twesleyb** [fawda123/rStrava#51]
Hi Marcus,

Thanks for making this really cool package. 

I think a great feature to add to rStrava would be the ability to export/download a GPX track.
Would this be possible? The python [code](https://developers.strava.com/docs/reference/#api-Routes-getRouteAsGPX) seems so simple, but I was unable to translate this to R.

Thanks again!
-Tyler

**Comment by fawda123** [comment]
Hi Tyler, I wasn't able to get anything from the API using any of my activity IDs, but was able to get something when I fed it my athlete id (and token).  However, I didn't recognize the lat/lon for the GPX track so I'm not sure what I downloaded. 

```r
library(XML)
library(httr)
library(tidyverse)

url <- "https://www.strava.com/api/v3/routes/2837007/export_gpx" 
req <- httr::GET(url, stoken)
dat <- httr::content(req)

pfile <- htmlTreeParse(req, error = function (...) {}, useInternalNodes = T)

# extract coordinates, make tibble
coords <- xpathSApply(pfile, path = "//trkpt", xmlAttrs) %>% 
	t %>% 
	as.tibble %>% 
	mutate(
		lat = as.numeric(lat),
		lon = as.numeric(lon)
	)

plot(lat ~ lon, coords, type = 'l')
```
![image](https://user-images.githubusercontent.com/3086881/51851412-b535e800-22d8-11e9-8b12-42a81816b311.png)

Not sure this is helpful, but maybe try messing around with some of the code on [this blog](https://rcrastinate.blogspot.com/2014/09/stay-on-track-plotting-gps-tracks-with-r.html).

**Comment by fawda123** [comment]
And for what it's worth, we do have a function already that decodes the Google polylines that are returned with the activity requests, though it's only lat/lon. 

```r
my_acts <- get_activity_list(stoken)
act_data <- compile_activities(my_acts)
decode_Polyline(act_data$map.summary_polyline[1])
```

**Comment by twesleyb** [comment]
Hi Marcus,

Thank you!
I was able to download a GPX track using your example above, but like you the lat and lon made no sense.

The blog looks really helpful, but actually your decode_Polyline function may already do what I need it to do!

Also, I realized that with the get_activity_streams() function I can get lat/lon and elevation. I should be able to work with this!

**Comment by twesleyb** [comment]
Okay, for whatever reason the lat/lon from the `get_activity_streams()` function are not correct. 
The lat/lon from `decode_Polyline()` are correct. I can extract these and write to .gpx.

**Comment by fawda123** [comment]
Thanks, I'll check the lat/lon for `get_activity_streams()`.  They should be different but only in resolution.
