### ISSUE TITLE
Unable to pull friends' activities

### ISSUE THREAD

**Issue by mtengelin** [fawda123/rStrava#52]
I saw that the function get_activity_list() should be able to pull the activities of friends as well. However, when trying it I get the following error:

```
> my_acts <- get_activity_list(stoken, friends = TRUE)
Error in get_pages(url_activities(id = id, club = club, friends = friends),  : 
  Unauthorized (HTTP 401).
```

**Comment by fawda123** [comment]
Yea sorry, I don't think that option ever worked.  It was added by one of the other developers on this package, perhaps for a feature that no longer is available on the API.  I looked at the API documentation and couldn't find anything related to pulling activities for your followers - which is in line with what I think is Strava's policy to only allow a user to get detailed info about their activities.  Best you can do is scrape data from the public website using `athl_fun()`.  Sorry!

And FWIW, I just removed these non-functional feature from the package.  80b59bfbdf28b6874da49da8e3ff0eb07d9f1e59
