### ISSUE TITLE
Unable to update package from github: Error in FUN(X[[i]], ...) : is.remote(remote) is not TRUE

### ISSUE THREAD

**Issue by chrisbillingham-mago** [fawda123/rStrava#56]
Hi there,

When I try to update my rStrava package via github I get the following error:

`devtools::install_github("fawda123/rStrava")
Downloading GitHub repo fawda123/rStrava@master
Error in FUN(X[[i]], ...) : is.remote(remote) is not TRUE`

I've tried deleting and reinstalling the package as well but get the same error.

**Comment by fawda123** [comment]
The recent version added some new dependencies and the install might be having trouble grabbing those packages.  Try installing rvest, V8, and xml2 from CRAN, then reinstall rStrava.
