### ISSUE TITLE
Failed to get access token

### ISSUE THREAD

**Issue by egostus** [fawda123/rStrava#57]
I follow your instuctions, but get an error message.

> token <- httr::config(token = strava_oauth(app_name, app_client_id, app_secret))
> Waiting for authentication in browser...
> Press Esc/Ctrl + C to abort

I then go to the browser and click authorize. and gets the following in R

> Authentication complete.
> Error in oauth2.0_access_token(endpoint, app, code = code, user_params = user_params,  : 
>   Unauthorized (HTTP 401). Failed to get an access token.

Has there been any changes, so that the functions are not up-to-date?

**Comment by fawda123** [comment]
The package was recently updated to v1.0.0 (https://github.com/fawda123/rStrava/releases/tag/v1.0.0).  There were no changes made to the authentication protocol, but try reinstalling the package and getting a new API key from Strava.

**Comment by CarterMcC74** [comment]
Hello,

I have recently installed the package and I am experiencing the same error:

Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
Error in oauth2.0_access_token(endpoint, app, code = code, user_params = user_params,  : 
  Unauthorized (HTTP 401). Failed to get an access token.

Any advice?

**Comment by fawda123** [comment]
@CarterMcC74 are you working on a machine that's behind a firewall or any other network restrictions?  Have you tried on another computer? 

You might also try checking out the Strava API documentation, perhaps even setting up another API key and/or changing your access settings on your Strava app page.  

This documentation may also help.  https://developers.strava.com/docs/authentication/

**Comment by CarterMcC74** [comment]
@fawda123 I ended up getting it to work by redirecting the website requirement to the homepage of strava rather than my unique profile on their website when setting up the API. 

Thanks for reaching out!

**Comment by fawda123** [comment]
Thanks for the update @CarterMcC74. I'm sure this will help others having the same issue.
