### ISSUE TITLE
Number of activities with get_activity_list ?

### ISSUE THREAD

**Issue by susay** [fawda123/rStrava#58]
Hi, 
I'd like to read the activities of a club. I received a different number of results each time.  What does it depend on (about 100) and how can I read out more?

list_club <- get_activity_list(stoken, id = myClub_id, club = TRUE)
View(list_club)

**Comment by fawda123** [comment]
The club retrievals are limited to the first 200 https://github.com/fawda123/rStrava/blob/cd08f34ce07c539077102e50e5b1a08f656d69e7/R/get_activity_list.R#L48

We could easily add an argument to change this if you like, but can you please tell me the club Id you are using?

**Comment by susay** [comment]
The club Id is'329240'. Today I was able to read out 99 entries but on the website I can see more entries with the link: https://www.strava.com/clubs/329240/recent_activity 
An argument for the limit would made sense but I'm afraid it doesn't solve my problem.
My actual goal would be to analyze the data of this club for the whole past year. But last activities are only the last week anyway. That's a pity.

**Comment by fawda123** [comment]
Yea, Strava has gotten a bit more restrictive with what's available on the public API.
