### ISSUE TITLE
create activity maps?

### ISSUE THREAD

**Issue by fawda123** [fawda123/rStrava#6]
@padpadpadpad Any chance you can wrap up the new functions you added in a single function to create an activities heat map?  Seems simple enough but I think you already have the code, yes?

**Comment by fawda123** [comment]
Here's some code I put together for a single activity with ggmap.  This is my commute today :)  Should be pretty easy to wrap for all in the list, or just have this as a stand-alone function?  
```r
library(rStrava)
library(tidyr)
library(dplyr)
library(ggmap)

# activities list
acts <- get_activity_list(stoken, 2837007) %>% 
	compile_activities

# lat/lon for latest activity
tmp <- decode_Polyline(acts$map.summary_polyline[1]) %>% 
	separate(latlon, c('lat', 'lon'), sep = ',') %>% 
	mutate(
		lat = as.numeric(lat), 
		lon = as.numeric(lon)
	)

# base map
bmap <- get_map(
  location = c(lon = mean(tmp$lon),lat = mean(tmp$lat)),
  source = 'google',
  maptype = 'terrain',
  messaging = FALSE, 
	zoom = 12
  )

# plot single activity
ggmap(bmap, extent = "panel") + 
  geom_path(data = tmp, aes(x = lon, y = lat))
```

![rplot](https://cloud.githubusercontent.com/assets/3086881/18352459/1c200076-75a4-11e6-80fc-e5c41f46c7ce.png)

**Comment by padpadpadpad** [comment]
Looks good will have a play. Think it would be beneficial to have a couple of steps with get_activity_list() and compile_activities() and then a function that gives you a map of a number of rides but allow that to vary, so either 1 or many activities. Will have a play over the weekend and see what I come up with.

**Comment by padpadpadpad** [comment]
Got something done.

```{r}
# packages
library(rStrava)
library(tidyr)
library(dplyr)

# download the data
my_acts <- get_activity_list(my_token, id = '2140248')

# list to dataframe
MyActs <- compile_activities(my_acts)

# a bunch of transformations
# transformations of data
MyActs <- mutate_at(MyActs, c('average_cadence', 'average_heartrate', 'average_speed', 'average_watts', 'distance', 'elapsed_time', 'elev_high', 'elev_low', 'kilojoules', 'suffer_score', 'max_heartrate', 'max_speed', 'moving_time', 'total_elevation_gain'), as.numeric) %>%
  mutate(.,
         activity_no = seq(1,nrow(.), 1),
         distance = distance/1000,
         elapsed_time = elapsed_time/60/60,
         moving_time = moving_time/60/60,
         average_speed = average_speed*60*60/1000,
         max_speed = max_speed*60*60/1000,
         elevation_per_km = total_elevation_gain/distance,
         date = gsub("T.*$", '', start_date) %>%
           as.POSIXct(., format = '%Y-%m-%d'),
         month = format(date, "%m"),
         day = format(date, "%d"),
         year = format(date, "%Y")) %>%
  mutate_at(., c('month', 'day', 'year'), as.numeric) %>%
  group_by(year) %>%
  mutate(cum.distance = cumsum(distance)) %>%
  data.frame()

# get latest map
get_heat_map(MyActs[1,], alpha = 1)

# get all rides from a certain place (Cornwall for me)
get_heat_map(filter(MyActs, location_city %in% c('Mabe Burnthouse', 'Falmouth', 'Penryn', 'Budock Water', 'Helston', ' Mylor', 'Helston, UK', 'Saint Erth', 'Saint Ives', 'Scorrier')))

```

![heatmap_plot_single](https://cloud.githubusercontent.com/assets/10220722/18410196/0ce462a4-7753-11e6-9127-10d9d258a2ce.jpeg)
![heatmap_plot_cornwall](https://cloud.githubusercontent.com/assets/10220722/18410195/0cb964d2-7753-11e6-8c3a-14587d4faa28.jpeg)



Will add a pull request. Am looking to write a blog post about this soon as well because its rather neat.

**Comment by fawda123** [comment]
Awesome, thanks for the pull request on this. I have a blog on r-bloggers that I sometimes use, maybe we could post there? I haven't written about this package yet as I was waiting for some more dev so now seems like a good time. What do you think?
