### ISSUE TITLE
`athlind_fun` does not return year-to-date data or an all-time summary.

### ISSUE THREAD

**Issue by brndngrhm** [fawda123/rStrava#63]
I'm currently trying to recreate the summary that Strava provides on their website for the most recent 4 weeks, year to date, and all-time.  I noticed the documentation for `athlind_fun` states it returns "A list with elements for the athlete id, units of measurement, location, monthly data, year-to-date data, and an all-time summary." but when i run it, I only get the following:
- name
- location
- units
- monthly
- recent
- achievements

It doesn't seem to return year-to-date data or an all-time summary. I'm using package version 1.1.0.

btw I love this package! i made a dashboard with it to track my rides: https://brndngrhm.shinyapps.io/RideTracker/

**Comment by fawda123** [comment]
Very cool dashboard!  Unfortunately, the year-to-date and all-time summaries can't be scraped from the HTML.  I think these tables are loaded with JavaScript, which require a different set of tools (see [here](https://community.rstudio.com/t/scraping-table-weirdness-with-rvest-undesired-xml-nodeset-0/6798/)). Also see my response to #53.

**Comment by fawda123** [comment]
Added the help wanted label to see if anyone knows how to parse JavaScript loaded tables from within an R package.
