### ISSUE TITLE
athlind_fun errors out when strava members has privacy settings

### ISSUE THREAD

**Issue by duncan-clark** [fawda123/rStrava#64]
Would it be useful to have the function return NAs when it can't scrape the data?

**Comment by fawda123** [comment]
Yea I can do that, or better yet, return an informative error message. Can you please provide a user ID  I can use as an example?

**Comment by duncan-clark** [comment]
Try 11055606, it should be private so not scrape-able.

**Comment by fawda123** [comment]
Alright, how about this (16ed3a250be7f243e9ea2c7f51c03191d68995e1): 

```r
athl_fun('11055606')
# 11055606 1 of 1 
# $`11055606`
# [1] "No data for athlete 11055606, sharing permissions likely set to private."
```

**Comment by duncan-clark** [comment]
Thanks, looks good
