### ISSUE TITLE
app_scope now required when creating authentication token

### ISSUE THREAD

**Issue by ChrisWoodsSays** [fawda123/rStrava#67]
Following Strava's updates to the API which are mandatory from October 2019, an appropriate app_scope is now required, so the mark down file needs a minor update.

The line to below needs to be changed from:
`stoken <- httr::config(token = strava_oauth(app_name, app_client_id, app_secret))`

to:
`stoken <- httr::config(token = strava_oauth(app_name, app_client_id, app_secret, app_scope="activity:read_all"))`

Assuming private activities are to be read.  

For full details including other scope please refer to the [Strava API OAuth Updates page.](https://developers.strava.com/docs/oauth-updates/)

Thanks,

Chris.

**Comment by tmikolajczyk** [comment]
@ChrisWoodsSays, thanks for the comment!!! Your code indeed fixes the problem. Should be merged into master

**Comment by ChrisWoodsSays** [comment]
Thanks @tmikolajczyk . I've added it to my first ever pull request!  Any help you can give with my other issue (#66) would be greatly appreciated.

**Comment by tmikolajczyk** [comment]
I'm not an author or contributor of this package 😂 I just needed your solution. Anyway, apart from readme files update, the function itself should also be updated (`R/strava_oauth.R`) and its manual (just run `devtools::document` and its done).

**Comment by ChrisWoodsSays** [comment]
I've amended the function. Can't work out how to run devtools::document.

**Comment by tmikolajczyk** [comment]
just type `devtools::document()`. and R file should be updated not only in roxygen part but most of all in the body (line 18)

**Comment by fawda123** [comment]
Thanks @ChrisWoodsSays for the PR, working now!
