### ISSUE TITLE
creating elevation profile from Google polyline

### ISSUE THREAD

**Issue by padpadpadpad** [fawda123/rStrava#7]
I have code I had for raw .gpx files to find difference in distance between lat lon points. There are functions to get the elevation at each lat lon point. I wonder whether its possible to get an elevation profile for each ride.

**Comment by padpadpadpad** [comment]
Here is what I have so far. Uses access to the Google API using rgbif for elevation data...

Not really sure how not to use for() loops for the distance() function but does the job. Resolution is not as smooth as the raw .gpx data but is limited by the number of points from the google polyline. 

``` r
library(dplyr)
library(ggplot2)
library(tidyr)
library(rgbif)

# Google elevation API key
GoogleAPI <- 'Need another API'

# get my activities
my_acts <- get_activity_list(my_token, id = '2140248')

# turn activities into data frame
single_act <- compile_activity(my_acts[1])
MyActs <- compile_activities(my_acts)

# create a dataframe of long and latitudes
lat_lon <- get_all_LatLon(id_col = 'activity_no', parent_data = MyActs) %>%
  full_join(., MyActs, by = 'activity_no') %>%
  select(., c(activity_no, type, date, latlon, location_city)) %>%
  separate(., latlon, c('lat', 'lon'), sep = ',') %>%
  mutate_at(., c('lat', 'lon'), as.numeric) 

# function for working out distance from longitude and latitude points ###
distance <- function(dat, lon, lat){
  
  # column for distance
  x <- rep(0, times = nrow(dat))
  
  for(i in 2:nrow(dat)) {
    x[i] = sp::spDistsN1(as.matrix(dat[i,c(lon, lat)]),
                     as.matrix(dat[i - 1,c(lon, lat)]),
                     longlat = TRUE) 
    
  }
  return(cumsum(x))
}

distances <- group_by(lat_lon, activity_no) %>%
  do(data.frame(distance = distance(.,  'lon', 'lat')))
lat_lon$distance <- distances$distance

# adding elevation using rgbif
lat_lon$ele <- rgbif::elevation(latitude = lat_lon$lat, longitude = lat_lon$lon, key = GoogleAPI)$elevation

ggplot(data = filter(lat_lon, activity_no == 1), aes(x = distance)) +
  geom_ribbon(aes(ymax = ele, ymin = min (ele) - ((max(ele) - min(ele))/5)), fill = 'dark blue') +
  theme_bw() +
  ylab('Elevation (m)') +
  xlab('Distance (km)')

```

![elevation_single](https://cloud.githubusercontent.com/assets/10220722/18418496/7a3d59ea-783f-11e6-9625-cf5abd8bea05.jpeg)

**Comment by fawda123** [comment]
Cool, I was trying to get this working but was having some issues installing rgbif.  I think I'm having connectivity issues so will try again later.

**Comment by padpadpadpad** [comment]
Nay worries

Have had a little play and an equivalent function is:

```r
library(rgbif)
library(geosphere)

# distance function 1
distance <- function(dats, lon, lat){
  dat <- data[,c(lon, lat)]
  x <- sapply(2:nrow(dat), function(y){sp::spDistsN1(as.matrix(dat[y-1,c(lon, lat)]),
                                             as.matrix(dat[y,c(lon, lat)]),
                                             longlat = TRUE) 
  })
  return(c(0, cumsum(x)))
}


# distance function 2
distance2 <- function(data, lon, lat){
  dat <- data[,c(lon, lat)]
  # column for distance
  x <- sapply(2:nrow(dat), function(y){geosphere::distm(dat[y-1,], dat[y,])/1000})
  return(c(0, cumsum(x)))
}

```

Either can be substituted for the other and get almost identical results...

`distance2()` is around twice as fast though. And that is the first time I have ever timed any piece of my code! 

May need to add an argument for units for most of these functions as people will prefer different things...

**Comment by fawda123** [comment]
What about this? 2f07d41a6cc3337a9f8f6c467857f8eb5408e617

Just added `get_elev_prof`, see the README example...

**Comment by padpadpadpad** [comment]
Looking good to me. As a base function I think it is great but I do think it is worth a stand alone function for distance so people can make their own graphs if they like.

Adding 'total elevation' onto the graph as well would be a nice addition.

This is a great way to show people what is possible to get them to extend the plots as they please.

**Comment by fawda123** [comment]
73344da2b457d4d077d115089583181e518baab8

Added a `total` argument to `get_elev_prof`, also created the `get_dists` function`

**Comment by padpadpadpad** [comment]
Really like the total function! What I meant was actually to incorporate the ele_tot from the activities. Has been done in the latest pull request. 

Might be nice to have the facet as a table inside or outside the graph. Will have a play.

**Comment by fawda123** [comment]
Thanks, yea I confused cumulative elevation with total, thanks for the PR.
