### ISSUE TITLE
Authentication complete but error

### ISSUE THREAD

**Issue by nurandi** [fawda123/rStrava#70]
I completed in-browser authentication 
```
Authentication complete. Please close this page and return to R.
```
But failed to get an access token
```
Authentication complete.
Error in oauth2.0_access_token(endpoint, app, code = code, user_params = user_params,  : 
  Unauthorized (HTTP 401). Failed to get an access token.
```

**Comment by nurandi** [comment]
Fixed!

**Comment by nurandi** [comment]
Fixed!

**Comment by CarterMcC74** [comment]
> Fixed!
Hello,

I have been having the same issue with mine despite clicking access when the pop up window prompts me. Any tips on how you got yours to work? 

Thanks!
