### ISSUE TITLE
get_activity_streams() with types list

### ISSUE THREAD

**Issue by matt-s-gibbs** [fawda123/rStrava#71]
I'm finding I get an error with trying to get a subset of data types from get_activity streams. If I use the same variables as the Readme for my_acts and stoken (once authenticated against my account):

strms_data <- get_activity_streams(my_acts, stoken, acts = 1, types=list("time","heartrate","distance","velocity_smooth"))

Error in map_lgl(.x, .p, ...) : object 'altitude' not found

Nice package, thanks for making it available.

**Comment by fawda123** [comment]
Should be fixed now 4d530112e682473542a8400943008bc90f7bd19d

**Comment by matt-s-gibbs** [comment]
Yep, that's fixed it, thanks for quick update! Also dealt with getting the stream for indoor activity that didn't have GPS (e.g. treadmill).
