### ISSUE TITLE
get_activity_streams ERROR if there are any manual activity on act_data

### ISSUE THREAD

**Issue by nurandi** [fawda123/rStrava#72]
`Error in get_streams(stoken, id = x) : Not Found (HTTP 404).`
 
Suggested enhancement: filter out all `manual = TRUE` activities from `act_data` before calling `get_streams` function

**Comment by fawda123** [comment]
Thanks for catching that, I added a check in `get_activity_streams()` to throw a more informative error if manual entries are present in the request.  Does that help? 

See the commit here: f2590fc3b92935b6c8192db094ec240aaef0eb27

```r
strms_data <- get_activity_streams(my_acts, stoken, id = 2839600813)
# Error in get_activity_streams.actframe(act_data, stoken, types = types,  : 
# Cannot get streams for manual activities: 2839600813
```

**Comment by nurandi** [comment]
Awesome! Thanks
