### ISSUE TITLE
athl_fun fails for any athlete ID: SyntaxError: Unexpected token :

### ISSUE THREAD

**Issue by adolgushin** [fawda123/rStrava#75]
Hi Marcus,

I am new to github so apologies if there's something wrong about this issue I am opening.

I am poking around with your library and the very first thing I am trying to do is calling athl_fun function. However I am always getting an error below (by googling I can see it is probably in the V8 package). I am making a guess Strava has changed the layout of the public HTML page which impacted this function.

> Error in context_eval(join(src), private$context, serialize) : 
>   SyntaxError: Unexpected token :

I am doing this in R console which all produce the error above; the Strava public pages are available in the browser:

```
> rStrava::athl_fun("2837007", trace = FALSE)
> rStrava::athl_fun(2837007, trace = FALSE)
> rStrava::athl_fun(38663744, trace = FALSE)
```

Thanks,
Andrei

**Comment by fawda123** [comment]
@adolgushin sorry about the delay on this, should be fixed now 86e44cd20a2704681efa1de942461e6bfd83f4f2
