### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by nsacco** [fawda123/rStrava#77]
Hi,
I am trying to use this package but when I try to install it in RStudio I get this error: "Error: Failed to install 'rStrava' from GitHub:
  (converted from warning) unable to access index for repository http://cloudyr.github.io/drat/bin/macosx/contrib/4.0:
  cannot open URL 'http://cloudyr.github.io/drat/bin/macosx/contrib/4.0/PACKAGES'"

**Comment by fawda123** [comment]
Looks like the installation is failing when it tries to install the drat dependency.  This is not a suggested import for rStrava, so it must be a dependency from one of the other packages that rStrava uses.  Try installing drat directly from [CRAN](https://cran.r-project.org/web/packages/drat/index.html) first, then try reinstalling rStrava.

**Comment by nsacco** [comment]
Yes, was that I thought was an issue with the package, thank you.
