### ISSUE TITLE
[Feature Request] Add `start_date` argument `get_activity_list`

### ISSUE THREAD

**Issue by michaellevy** [fawda123/rStrava#79]
I'd like to save activities locally and just pull new ones. I know the old Strava API could do this but haven't checked the new one. Is this something you think would be worthwhile?

**Comment by fawda123** [comment]
@michaellevy I think this should work.  There are `before` and `after` options in the v3 API that allow "epoch timestamps" as input to the API query.  I added two optional arguments to `get_activity_list` that accept Date objects for min/max dates to limit the query.  

```
my_acts <- get_activity_list(stoken, after = as.Date('2019-10-01'), before = as.Date('2020-01-01'))
act_data <- compile_activities(my_acts) 
range(act_data$start_date_local)
# [1] "2019-10-02T07:12:11Z" "2019-12-27T11:10:44Z"
```

**Comment by michaellevy** [comment]
Works great, thank you very much!
