### ISSUE TITLE
Cannot install package because of incompatibility with XML?

### ISSUE THREAD

**Issue by EricBWeiner** [fawda123/rStrava#80]
I want to preface this with i'm somewhat new to R and RStudio. I'm running RStudio 1.2.1335 on Mac. 

I attempted to run the first two install lines of this package and Console has a list of packages that rStrava recommends 27 versions to update. I selected to update ALL. 

```
install.packages('devtools')
devtools::install_github('fawda123/rStrava')
```

Once it completes Console gives the following message
```
ERROR: dependency ‘XML’ is not available for package ‘rStrava’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/rStrava’
Error: Failed to install 'rStrava' from GitHub:
  (converted from warning) installation of package ‘/var/folders/zm/bfkdkc2536v2bwsg85d3dl0m0000gp/T//RtmpgUYcOK/file1ded4722613b/rStrava_1.1.4.tar.gz’ had non-zero exit status
```

It seems as though I cannot install it. Do you have any thoughts?

**Comment by fawda123** [comment]
@EricBWeiner this is a weird thing that happens sometimes when installing packages from GitHub.  Just try installing XML first and then try reinstalling rStrava.  It's possible you'll get a similar message for other packages, so just rinse and repeat.

**Comment by EricBWeiner** [comment]
@fawda123 Thank you much for the reply. I ran `install.packages('xml')` independently and it gave a warning of `package ‘xml’ is not available (for R version 3.6.1)` and then said `Skipping 1 packages not available: XML`. I have the Package xml2 available in RStudio but enabling that still won't let rStrava install. 

Any other suggestions?

**Comment by fawda123** [comment]
The package name should be all capitalized.

**Comment by EricBWeiner** [comment]
`install.packages('XML')` provides a similar message of `package ‘XML’ is not available (for R version 3.6.1)`

**Comment by EricBWeiner** [comment]
@fawda123 after some more research I upgraded my R to current version 4.0.2 and the rStrava package and associated elements installed without issue. Totally my fault. Thanks for the feedback though as it helped point me in the right direction.

**Comment by fawda123** [comment]
@EricBWeiner no worries, updating R would have been my next suggestion :)
