### ISSUE TITLE
Pull Segment with Date parameters to include user IDs?

### ISSUE THREAD

**Issue by EricBWeiner** [fawda123/rStrava#81]
As I read through the documentation I don't see parameters to perform queries for Segment analysis. Specifically, I'm looking to query on a specific Strava Segment, and return all results within a particular timeframe. E.g. Return all entries for segment 2734076050935180936 between startDate and endDate. I see [Strava API has Segment Efforts](http://developers.strava.com/docs/reference/#api-SegmentEfforts-getSegmentEffortById) and am wondering if you've ported this over to R? Ultimate goal is to support a virtual event we're hosting to compare specific segments for a list of specific riders within a 14 day window and then output all results for analysis to plot, review , etc. 

Not an "issue" - thanks in advance.

**Comment by fawda123** [comment]
@EricBWeiner yes, you can do that with the `get_efforts_list()` function: https://fawda123.github.io/rStrava/reference/get_efforts_list.html

However, this requires a paid subscription, which they must have recently changed because I can't use the function anymore.

**Comment by EricBWeiner** [comment]
Thanks for the response. I figured it out eventually but realized that Strava limits queryable data to members' own data only. Therefore my goal of pulling segment data for multiple people is a dead end. Unless I get each person to authorize the app, but that's way too much work. I appreciate the feedback.
