### ISSUE TITLE
Issue with compile_seg_effort()

### ISSUE THREAD

**Issue by pbarban** [fawda123/rStrava#82]
Hey,

Just wanted to let you know that the compile_seg_effort() fucntion does not work properly. 

After getting a list of all the effort of an activity with get_efforts_list(), the compile_seg_effort() will not compile the efforts where the athlete ranked a new top score on that specific segment. 

From an R perspective, I believe that it caused by the unequal number of columns for each row. The effort with a new record will have a ranking value whereas efforts without records will not have anything.

thank you for your help and time!

**Comment by fawda123** [comment]
@pbarban thanks for the heads up, can you reinstall and try it again?  I've attempted a fix, but I can't test it because I don't have the right pay plan.

**Comment by pbarban** [comment]
@fawda123 I made sure to reinstall it but there is still the same issue. Please let me know if there is anything I can do to help! I absolutely love that package :)

**Comment by fawda123** [comment]
@pbarban are you running code similar to this? What is the exact error you get?  Is it the exact same error as before?

```
stoken <- httr::config(token = strava_oauth(app_name, app_client_id, app_secret, cache = TRUE))

# segments to get efforts from
segment <- 2269028

# get segment efforts
efforts <- get_efforts_list(stoken, segment)
 
# compile efforts
efforts <- compile_seg_effort(efforts)
```
