### ISSUE TITLE
Not Found (HTTP 404).

### ISSUE THREAD

**Issue by briatte** [fawda123/rStrava#89]
I'm trying to access my own data. I successfully create a token with

```r
app_name <- '...'
app_client_id  <- '...'
app_secret <- '...'
stoken <- httr::config(token = strava_oauth(app_name, app_client_id, app_secret, app_scope="activity:read_all"))
```

However:

```r
get_activity_list(stoken, id = '88124XXX') # my Strava ID
```

… returns

```
Error in get_pages(rStrava::url_activities(id = "88124XXX"), stoken) : 
  Not Found (HTTP 404).
```

What am I doing wrong?

I checked everything at https://www.strava.com/settings/api -- client ID is correct, access token is fresh, secret is correct too.

**Comment by fawda123** [comment]
Hi @briatte, you don't need to include the `id` argument in the `get_activity_list()` function.  That argument is used for retrieving activities for a specific activity or club (if `club = TRUE`), not your Strava ID.  It should work if you omit the argument.

**Comment by briatte** [comment]
Hi @fawda123 -- sorry for the late reply, but thanks, that worked!
