### ISSUE TITLE
Package update with heat map addition

### ISSUE THREAD

**Issue by fawda123** [fawda123/rStrava#9]
Update readme, contributors

**Comment by fawda123** [comment]
@padpadpadpad What's a good email I can use for you?  I've added you as an author on the package.

**Comment by padpadpadpad** [comment]
dp323@exeter.ac.uk at the moment. Will be around for while.

Cheers
Dan

**Comment by fawda123** [comment]
e0ecfb7fc9ce990a57f7aeaf6fa9d6ab38d10d83
