### ISSUE TITLE
Add units to documentation for get_streams

### ISSUE THREAD

**Issue by arvi1000** [fawda123/rStrava#92]
I think it would be useful to include what units are returned for each stream type in the documentation. e.g. time is seconds, distance is meters. The info is provided in the developer reference (e.g. https://developers.strava.com/docs/reference/#api-models-TimeStream).

If others agree this is useful I could try to take this on and submit a pull request

**Comment by fawda123** [comment]
@arvi1000 thanks for the suggestion, I can certainly add this in the documentation but feel free to submit a PR!
